modules:
  - name: "Letters that Lead"
    lessons:
      - name: "Introduction"
        file: "01-introduction_letters.md"
        shortName: "intro-letters"
      - name: "Student Stories"
        file: "02-student_stories.md"
        shortName: "stories"
      - name: "Letter Writing"
        file: "03-letter_writing.md"
        shortName: "letter"
  - name: "Cal State LA Resources"
    lessons:
      - name: "Introduction"
        file: "R01-resources.md"
        shortName: "intro-resources"
      - name: "Time Management"
        file: "R02-time_management.md"
        shortName: "time-manage"
      - name: "Tutoring"
        file: "R03-tutoring.md"
        shortName: "tutoring"
      - name: "Study Groups"
        file: "R04-study_groups.md"
        shortName: "study-groups"
      - name: "Office Hours"
        file: "R05-office_hours.md"
        shortName: "office-hours"
      - name: "Concluding Questions"
        file: "R06-concluding_questions.md"
        shortName: "conclude"
  - name: "Reflecting on the Semester"
    lessons:
      - name: "How was it?"
        file: "S01-reflection.md"
        shortName: "reflect"